version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.8
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.8
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.2.8
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
